version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: ultra-discord-bot-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: UltraUniqLinks
    volumes:
      - mongodb_data:/data/db

  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env # read all env variables from .env
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

volumes:
  mongodb_data:
