version: '3.9'
services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./packages/server/.env # read all env variables from .env
    ports:
      - '3000:3000'
